#!/bin/sh

set -e

VALUE="$1"

if [ -z "$VALUE" ]; then
    VALUE="80"
fi

NAME="REDCAM RC-250: REDCAM RC-250"
CAMS=$(find /dev -name 'video*' -exec basename {} \; | sort)

for cam in $CAMS; do
    ct=$(v4l2-ctl -d /dev/$cam -D | grep -s "Card type" | grep -s "$NAME" || true)
    if [ -n "$ct" -a -n "$(v4l2-ctl -d /dev/$cam -l)" ]; then
        echo -n "${cam}: " && v4l2-ctl -d /dev/$cam --set-ctrl=saturation=$VALUE && echo 'ok' || echo 'failed'
    fi
done

