# BEGIN_KITTY_THEME
# Monokai
include current-theme.conf
# END_KITTY_THEME

font_family      Fira Mono for Powerline
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

#shell /home/longsleep/Dev/bin-scripts/tmux-terminal-helper
shell .

remember_window_size no
initial_window_width  720
initial_window_height 460

hide_window_decorations no
wayland_titlebar_color background

tab_bar_edge bottom
tab_bar_min_tabs 1
tab_bar_style slant

allow_remote_control no

enabled_layouts splits:split_axis=horizontal

map ctrl+b>- launch --location=hsplit --cwd=current
map ctrl+b>| launch --location=vsplit --cwd=current

map kitty_mod+/ launch --location=hsplit --allow-remote-control kitty +kitten kitty-kitten-search/search.py @active-kitty-window-id
map ctrl+b>/ launch --location=hsplit --allow-remote-control kitty +kitten kitty-kitten-search/search.py @active-kitty-window-id

map Alt+Insert kitten kitty_grab/grab.py
map kitty_mod+Left no_op
map kitty_mod+Right no_op
map Ctrl+Page_Up previous_tab
map Ctrl+Page_Down next_tab

